Fix issue w/ snow layers
ProjectKorra/ProjectKorra pull request #1116
Opened 2020-10-27 06:41 UTC by Varhagna

* Fixes unnecessary lambda expression assignment and simply passes is already existing data variable into TempBlock as to prevent issues.

Fill in whatever sections apply, feel free to remove any others. :thumbsup:

## Fixes
* Fixes snow melting throwing invalid argument exception in PhaseChange's melt function due to improper setting of block data.
    > * Fixes #1115

2020-10-28 11:36 UTC, PrimordialMoros requested changes

2020-10-28 11:36 UTC, PrimordialMoros commented on src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
>  					snow.setLayers(snow.getLayers() - 1);
Just remove this line so it doesn't double reduce the layers. Don't reuse the same blockdata

2020-11-06 18:28 UTC, ChristopherWMM approved these changes
Awesome! 👍

2020-11-06 18:43 UTC, Simplicitee approved these changes

2020-11-06 18:45 UTC, merged