Cooldown bug fixes, earth tunnel revert time
ProjectKorra/ProjectKorra pull request #1157
Opened 2021-06-16 22:22 UTC by Loonyy

- Fixes cooldown on Bloodbending not activating.
Previous would allow a user to constantly spam shift to Bloodbend without going on cooldown.
- Fixed FireManipulation stream cooldown not being applied
- Adds separate revert time for EarthTunnel
In general on servers you want a small revert time for arena's, but you can't do that because people get trapped in EarthTunnel in survival because it resets so quickly.

2021-06-17 16:37 UTC, Simplicitee requested changes

2021-06-17 16:37 UTC, Simplicitee commented on src/com/projectkorra/projectkorra/configuration/ConfigManager.java
> +			config.addDefault("Properties.Earth.EarthTunnel.RevertCheckTime", 30000);
this should still follow the convention of `Abilities.<element>.<ability>.<option>` so the path should be `Abilities.Earth.EarthTunnel.RevertCheckTime`, reason being so we keep all the ability-specific information within the ability's section of the config.

2021-06-17 16:37 UTC, Simplicitee commented on src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java
> +		this.revertTime = getConfig().getLong("Properties.Earth.EarthTunnel.RevertCheckTime");
this should also be changed to reflect the change in the other comment

2021-07-06 20:05 UTC, ChristopherWMM commented
@Loonyy are you able to make the requested changes?

2021-07-17 16:59 UTC, ChristopherWMM approved these changes
Looks good! :+1:

2021-07-17 17:07 UTC, Simplicitee approved these changes

2021-07-17 17:15 UTC, merged