Add Lightning Sounds + Configurable options for them
ProjectKorra/ProjectKorra pull request #1161
Opened 2021-07-06 22:42 UTC by greenwolf5

## Additions
* Adds LightningCharge sound effect, with a method playLightningbendingChargingSound located in FireAbility, that gets called in Lightning when the move is charging. Allows config support following the similar structure of LightningSound
* Adds LightningHit sound effect, with a method playLightningbendingHitSound located in FireAbility, that gets called in Lightning when the move hits an entity. Allows config support following the similar structure of LightningSound
* Adds playLightningbendingSound() when the lightning is progressing

##Misc changes
* updated the pom.xml to https since it was found maven doesn't support the previous method

2021-07-07 00:26 UTC, ChristopherWMM commented
Thank you for your contributions, we really appreciate it! That being said, there are a few things we were hoping you could change to make this PR something we would consider merging.

1. Right now, you are including some old commits due to your branch being out of date with `wip`. Ideally, your PR should only include the new commits you are making.
2. There are some miscellaneous comments that are not super necessary. We would prefer that these are removed. Specifically, the following:
    - https://github.com/ProjectKorra/ProjectKorra/pull/1161/files#diff-618fee85c0577a7dd0a34f0f8c56e9f4e84729c5de56a4650bcf80df75eac8c3R210-R211
    - https://github.com/ProjectKorra/ProjectKorra/pull/1161/files#diff-7b451201bde2696c679a9996f0759b16b113eff19cd6ea33935cd3eb51d7e691R215
    - https://github.com/ProjectKorra/ProjectKorra/pull/1161/files#diff-7b451201bde2696c679a9996f0759b16b113eff19cd6ea33935cd3eb51d7e691R251
3. If you are going to add documentation comments to methods, I would prefer that they be standard javadocs.
4. In Lightning.java, you create a new `Random` object for each instance. It would be better to use `Math.random()` or better yet [ThreadLocalRandom](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/concurrent/ThreadLocalRandom.html) to prevent having to make new Random objects. If this is new, check out [this post](https://www.baeldung.com/java-thread-local-random#threadlocalrandom-example) for more info.

Please feel free to reach out if you have any questions or need help making the above changes!

2021-07-11 01:36 UTC, ChristopherWMM requested changes

2021-07-11 01:36 UTC, ChristopherWMM commented on src/com/projectkorra/projectkorra/ability/FireAbility.java
> +			} finally{
You should have a space after `finally`.

```java
} finally {
```

2021-07-11 01:36 UTC, ChristopherWMM commented on src/com/projectkorra/projectkorra/ability/FireAbility.java
> +			}	finally {
There should be a space between the closing brace of the catch and finally, not a tab.

```java
} finally {
```

2021-07-11 01:36 UTC, ChristopherWMM commented on src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
> +					if(ThreadLocalRandom.current().nextDouble() < .2){
There should be a space between the if and opening parenthesis. Additionally, there should be a space between the closing parenthesis and the opening brace.

```java
if (ThreadLocalRandom.current().nextDouble() < .2) {
```

2021-07-11 01:36 UTC, ChristopherWMM commented on src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
>  		if (Math.random() <= this.stunChance) {
Might as well change this and other instances of `Math.random()` to use `ThreadLocalRandom.current().nextDouble()`

2021-07-11 01:36 UTC, ChristopherWMM commented on src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
> +				if(ThreadLocalRandom.current().nextDouble() < .2){
There should be a space between the if and opening parenthesis. Additionally, there should be a space between the closing parenthesis and the opening brace.

```java
if (ThreadLocalRandom.current().nextDouble() < .2) {
```

2021-07-11 01:36 UTC, ChristopherWMM commented on src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
> +				if(ThreadLocalRandom.current().nextDouble() < .1){
There should be a space between the if and opening parenthesis. Additionally, there should be a space between the closing parenthesis and the opening brace.

```java
if (ThreadLocalRandom.current().nextDouble() < .1) {
```

2021-07-12 20:03 UTC, ChristopherWMM approved these changes
Great job! Thank you for working out all those requested details! 👍

2021-07-17 16:42 UTC, Simplicitee approved these changes

2021-07-17 16:44 UTC, merged