Fix (#1228)
ProjectKorra/ProjectKorra pull request #1230
Opened 2022-09-06 08:04 UTC by Igzak

Fix issue when bendingPlayer has only custom element not loading correctly from DB (#1228)

## Fixes
* Fixes
    > * [Link to GitHub Issue(s)](https://github.com/ProjectKorra/ProjectKorra/issues/1228)

2022-09-06 08:06 UTC, StrangeOne101 approved these changes

2022-09-06 21:32 UTC, StrangeOne101 commented
Actually, you don't change it for subelements. That's needed too

2022-09-07 04:34 UTC, StrangeOne101 requested changes
Looks good, except you need to do the same for subelements. I forgot at the time, so I approved. Sorry about that.

2022-09-08 11:32 UTC, Varhagna submitted a review, later dismissed
Looks good! Thanks for catching this, its much appreciated.

2022-09-08 11:50 UTC, merged