Add permission for each flight mode in Flight Multiability
ProjectKorra/ProjectKorra pull request #1318
Opened 2024-03-04 19:33 UTC by LucioMacarine

## Additions
* Added permission checks for Soar, Glide and Levitate in the Flight MultiAbility

2024-03-04 19:35 UTC, LucioMacarine commented
I'm new here so please point out anything that i might have done wrong. :heart:

2024-03-21 08:56 UTC, Varhagna approved these changes

2024-03-23 02:34 UTC, StrangeOne101 requested changes
I like what you are trying to do. But I think the changes you are making should be made more in MultiAbility. See my comments bellow about it.

In addition, you are also using the `wip` branch of PK. This branch is pretty old and isn't updated now, so try do it from `master` to `master`

2024-03-23 02:34 UTC, StrangeOne101 commented on src/com/projectkorra/projectkorra/airbending/flight/FlightMultiAbility.java
> +	private Map<FlightMode, Boolean> allowedFlightModes = new HashMap<>();
If you have a boolean for a value in a map, you may as well just use a Set. And use `Set#contains`

2024-03-23 02:34 UTC, StrangeOne101 commented on src/com/projectkorra/projectkorra/airbending/flight/FlightMultiAbility.java
> +			.filter(mode -> this.allowedFlightModes.get(mode)).findFirst();
While I like what you are trying to achieve, I think this sort of thing should be implemented for multiabilities as a whole. Right now, WaterArms supports permissions for each subability, but they aren't removed from the list. So I think this functionality would be better suited to be fused into Multiabilities as a whole. And then WaterArms and flight are just updated to use the new system.

2024-03-23 02:34 UTC, StrangeOne101 commented
If the changes mentioned are too much, just copy how WaterArms does it for now while we figure out a better way to do it systematically

2024-03-24 02:59 UTC, LucioMacarine commented
I'll work on it soon

2024-03-28 01:00 UTC, LucioMacarine commented
As it turns out, the changes mentioned above were too much. ☹️
I deeply apologize but don't feel very confident changing that much. I tried to think of some ideas but they all had compromises and were just bad in general.

As for making it more like WaterArms, WaterArms only has to check the permission when a sub ability gets activated and not on startup that's why i added the first avaliable flight mode thing. So reverting to this PR's first commit would do exactly that i guess

And one more dumb question:
For me to be able to merge from master to master would i have to create another PR?

I truly apologize for wasting your times with this seemingly simple patch.

2024-03-28 01:04 UTC, StrangeOne101 commented
Don't apologize, these things happen.

I think you would have to create another PR to go from master to master.

2024-03-28 01:49 UTC, closed without merging