1.12.0 - Attribute & Day/Night factor overhaul + New AvatarState
ProjectKorra/ProjectKorra pull request #1340
Opened 2024-06-29 04:50 UTC by StrangeOne101

Lots of stuff to look at, so I'd recommend doing it commit by commit

# General Changes

## New `/b temp` command.
- A new command to add elements or subelements to players for a set period of time
- Time is in the format of `1d2h30m`
- `/b temp add <player> <element> <time>` - to add elements. Also allows for `avatar` and `all`. Will not stack time onto existing elements
- `/b temp remove <player> [element]` - to remove elements
- `/b temp extend <player> <element> <time>`  - to extend (or add if they don't have it) time to the specified elements
- `/b temp reduce <player> <element> <time>` - to reduce the time a player has on elements. If the end result is that the player has no more time with the element, it is removed.
- Will add subelements that the player has permission for that are bound to the parent element. E.g. adding water will add ice, plant, healing, etc. These subelements, however, do not have a time on their own.
- Elements that expired when a player is offline will tell the player they expired when they logged in
- Temp elements will show in `/b who` with a time attached to them

## Attribute Redo
- Attributes will now cache their initial value when the ability starts
- A new `AbilityAttributeRecalculateEvent` is now fired when an ability needs to calculate the value of attributes
  - This event can be fired with `CoreAbility#recalculateAttributes`
  - Day/Night factors now add their modifiers to this event to modify the value of the attribute
  - This allows multiple multipliers to be added to an attribute without loosing the original value of the attribute
- AvatarState now also hooks into this to change _any_ attributes.

## New AvatarState
- New AvatarState
  - New particles that appear while AvatarState is active
  - New particle that appear when AvatarState is activated
  - New AvatarState sound
  - Option for using AvatarState automatically on low health
    - Only works when AvatarState is bound to your abilities
    - Has configuration for whether it should save you from death
  - New configuration option to make the player glow
  - Any potion effect can be added/removed in the config
  - The cooldown now scales to how long the ability was active for
- New AvatarState config
  - Contains modifiers and values to set for every ability and every element
  - If an ability doesn't have any modifiers for attributes, it will use fallback modifiers defined for the element
  - Some keys from the old avatar config will migrate
  - Supports changing any value as long as the ability supports the `@Attribute` annotation
- AvatarState now feels way more overpowered compared to what it was before, and is now even more configurable
- AvatarState can now ignore chiblocking (configurable)

## Changes
- Decreased the amount of noise caused by RaiseEarth, ShockWave, Torrent (wave), Surge (wave)
- Day/Night messages no longer appear at the same time. In fact, there is now a small period at dawn/dusk where no bender gets a buff
- Updated AirBlast to work on new doors, trapdoors and buttons
- You can now sprint on AirSpout in AvatarState
- Made Bloodbending & MetalClips' actionbar message configurable
- Made IceWave's IceSphere radius configurable

## Fixes
- Fixed tags in the config not accepting non minecraft namespace tags (https://github.com/ProjectKorra/ProjectKorra/issues/1324)
- Fixed spamming the add command not saving all the added elements due to race condition (https://github.com/ProjectKorra/ProjectKorra/issues/1338)
- Fixed WaterArms flooding when moving the camera up (https://github.com/ProjectKorra/ProjectKorra/issues/1336)
- Fixed the damage handler having issues on 1.20.4 due to checking the wrong version
- Fixed Surge not replacing soul fire

# Dev Changes

## Additions
- New `@DayNightFactor` annotation. Marks if the attribute should be buffed during the day/night period for that element
- Added API to send PK branded messages using chat components
- Added API to reduce noise in Earth abilities
- Added CanBindHook for developers to override binding functionality. `BendingPlayer#registerCanBindHook`
- See Attribute Redo for the new event

## Changes
- Water/Fire Abilities no longer check for Day/Night to apply a modifier to values. This is now done in the new attribute event
- Abilities no longer check for AvatarState and apply the AvatarState modifier to values

## POM changes
- Removed accidental module-core etc folders
- Removed NoCheatPlus dependancy
- Removed timings depend that was left in one of the poms
- Updated dependancy for GriefDefender

2025-01-04 03:47 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/command/ChooseCommand.java
> +			});;
Double semi

2025-01-04 03:47 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/command/ChooseCommand.java
> +		});;
Double semi

2025-01-04 03:47 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/command/CooldownCommand.java
> +        });;
Double semi

2025-01-04 03:47 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/command/WhoCommand.java
> +		});;
Double semi

2025-01-04 03:47 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
>  			mh.stopWithDuration((long) this.stunDuration, Element.LIGHTNING.getColor() + "* Electrocuted *");
Should Lightning, Paralyze, and Immobilize which use `MovementHandler::stopWithDuration` also have their ActionBar message be configurable?

2025-01-04 22:41 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
>  			mh.stopWithDuration((long) this.stunDuration, Element.LIGHTNING.getColor() + "* Electrocuted *");
I agree they should be. But it was just out of the scope of what I did here and in my opinion, should be done in another update

2025-01-04 22:42 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/command/ChooseCommand.java
> +		});;
Lol GitHub copilot

2025-01-11 17:47 UTC, ChristopherWMM approved these changes

2025-01-11 17:47 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/ability/CoreAbility.java
>  	private void modifyAttributes() {
Is it okay that this now does nothing? Do you think a warning or something might be beneficial?

2025-01-11 17:52 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
>  			mh.stopWithDuration((long) this.stunDuration, Element.LIGHTNING.getColor() + "* Electrocuted *");
Once this gets merged, I'll make an issue for this 👍

2025-01-11 21:36 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/ability/CoreAbility.java
>  	private void modifyAttributes() {
Hmm. Never thought of that. While it isn't a bad idea, it could get spammy in the console. So maybe it's best as is. A silent "no longer works" vs "loud spammy warnings"

2025-01-13 04:30 UTC, PrideInt requested changes
@StrangeOne101 `TempCommand` and appropriate event firing might want to be addressed. Everything else looks good.

2025-01-13 04:30 UTC, PrideInt commented on core/src/com/projectkorra/projectkorra/event/PlayerChangeElementEvent.java
> +		TEMP_ADD, TEMP_REMOVE, TEMP_EXPIRE;
May want to fire a `PlayerChangeElementEvent` or `PlayerChangeSubElementEvent` event in `TempCommand.java`, so developers can actually track temp changes when listened for, like around here:
https://github.com/ProjectKorra/ProjectKorra/blob/551c6bbba0a750c068c3c94ffe201fe195570366/core/src/com/projectkorra/projectkorra/command/TempCommand.java#L174-L188

or within the `addElement`, `extendElement`, `reduceElement`, `removeElement` functions.

2025-01-13 04:30 UTC, PrideInt commented on core/src/com/projectkorra/projectkorra/util/DamageHandler.java
> +		if (entity.hasMetadata("BendingImmunity")) return;
Is "`BendingImmunity`" meant to be temporary or permanent? If the latter, we should use persistent data instead.

2025-01-13 09:38 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/ability/ElementalAbility.java
> +		return time >= 12750 && time <= 23250;
Why? Why would anyone ever do `!isDawn && !isDusk && !isNight && !isDay`. That's so dumb

2025-01-13 09:38 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/event/PlayerChangeElementEvent.java
> +		TEMP_ADD, TEMP_REMOVE, TEMP_EXPIRE;
Possibly an oversight

2025-01-13 09:38 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/util/DamageHandler.java
> +		if (entity.hasMetadata("BendingImmunity")) return;
Temporary.

2025-01-13 09:39 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/GeneralMethods.java
> +				|| (entity instanceof Player && ((Player) entity).getGameMode().equals(GameMode.SPECTATOR))) || entity instanceof ArmorStand && ((ArmorStand) entity).isMarker();
Didn't know this was a thing. Probably would be better

2025-01-13 09:46 UTC, PrideInt commented on core/src/com/projectkorra/projectkorra/ability/ElementalAbility.java
> +		return time >= 12750 && time <= 23250;
As in to check for world types with no time. But yeah, I'm thinking too deep with this and it would naturally make more sense to instead have some general function `isTimeless` or something or just depend on the developer to do whatever they need to do themselves. Again, just talking out loud so feel free to ignore.

2025-01-13 09:52 UTC, StrangeOne101 commented on core/src/com/projectkorra/projectkorra/ability/ElementalAbility.java
> +		return time >= 12750 && time <= 23250;
The main reason these methods exist is for day night factors. Addons don't really use them, and even then, it's not hard to copy the code from these methods and modify them to suit your needs

2025-01-13 22:24 UTC, ChristopherWMM commented on core/src/com/projectkorra/projectkorra/ability/ElementalAbility.java
> +		return time >= 12750 && time <= 23250;
I agree for the long run but my concern is that then this general use case becomes a little more obtuse to use. We shouldn't worry about that in this PR, it is far too large already.

2025-01-14 09:39 UTC, PrideInt approved these changes

2025-01-14 22:49 UTC, merged